permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 赵二
  email: 574098783@qq.com
  github: http://github.com/kunkazhao

# 站点信息
title: 赵二的博客 
description: 赵二的博客
url: http://www.zhaoer.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://i4.piimg.com/4851/81dceaacdcf56c25.jpg
favicon: http://i4.piimg.com/4851/81dceaacdcf56c25.jpg

# google analytics 设置
ga:
  id: UA-54767140-1
  url: www.zhaoer.me

# disqus 设置
disqus:
  shortname: zhaoer
