permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 赵二
  email: 574098783@qq.com
  github: http://github.com/kunkazhao

# 站点信息
title: 赵二的博客 
description: 赵二的博客
url: http://www.zhaoer.me
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7xpz5v.com1.z0.glb.clouddn.com/%E5%A4%B4%E5%83%8F.JPEG
favicon: http://7xpz5v.com1.z0.glb.clouddn.com/%E5%A4%B4%E5%83%8F.JPEG

# google analytics 设置
ga:
  id: UA-54767140-1
  url: www.zhaoer.me

# disqus 设置
disqus:
  shortname: zhaoer
